# your domain
domain: stupefied-bhabha-3bf8a2.netlify.app/

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - source.yaml
  # use web file
  - https://github.com/luohao10001/pps/raw/master/config/source.yaml
